config/routes.rb
Rails.application.routes.draw do
  devise_for :adeqo_users
  get 'adeqo_users/index'
  get 'adeqo_users/new'
  get 'adeqo_users/create'
 post 'adeqo_users/create'
  get 'adeqo_users/show'
  get 'create/new'
  get 'create/show'
  get 'users/index'
  get 'users/new'
  get 'users/create'
  get 'users/show'
  get 'users/error'
 post 'users/update'
# get 'users/downloadkwdump'
# resources :students
  resources :users
  resources :adeqo_users

  get 'welcome/index'
 #For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 #root 'application#hello'
 get 'welcome/homepage'

constraints subdomain: "alpha" do
        #get '/'=> redirect { |params| "http://alpha.adeqo.com/users/index" }
        get '/' => 'users#index'
end
  root 'welcome#homepage'

post 'users/downloadkwdump' => "users#downloadkwdump"
post 'users/updatead' => "users#updatead"

 get 'chris/test' => "chris#test"

post 'users/updateaccount' => "users#updateaccount"
post 'users/deleteaccount' => "users#deleteaccount"

post 'adeqo_users/updateuser' => "adeqo_users#updateuser"
post 'adeqo_users/deleteuser' => "adeqo_users#deleteuser"




end

app/models/adeqo_user.rb
class AdeqoUser < ApplicationRecord

  attr_accessor :password
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable
  #before_save :encrypt_password
  #after_save :clear_password

  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, :presence => true, :uniqueness => true, :format => EMAIL_REGEX
  validates :password, :confirmation => true #password_confirmation attr
  #Only on Create so other actions like update password attribute can be nil
  validates_length_of :password, :in => 6..20, :on => :create

  def encrypt_password
    if password.present?
      self.salt = BCrypt::Engine.generate_salt
      self.encrypted_password = BCrypt::Engine.hash_secret(password, salt)
    end
  end

  def clear_password
    self.password = nil
  end

end

app/controllers/adeqo_users_controller.rb
class AdeqoUsersController < ApplicationController

def index
	@adeqo_users = AdeqoUser.all
end

def new
	@adeqo_user = AdeqoUser.new
	render :layout => false
end

def create
	@adeqo_user = AdeqoUser.new(params[:adeqo_user].permit!)
	if @adeqo_user.save
		#redirect_to @adeqo_user, alert: "User created successfully."
		flash[:notice] = "You signed up successfully"
		flash[:color]= "valid"
		redirect_to "/adeqo_users"


	else
		#redirect_to adeqo_users_new_path, alert: "Error creating user."
		flash[:notice] = "Form is invalid"
		flash[:color]= "invalid"
		render "new", :layout => false
	end


end

def show
	@adeqo_users = AdeqoUser.find(params[:id])
end


def updateuser
        @adeqo_user =  AdeqoUser.find(params[:adeqo_user][:id])
	if @adeqo_user.update
		redirect_to @adeqo_user, alert: "User updated successfully."
	else
		redirect_to adeqo_users_new_path, alert: "Error updating user."
	end
end


def deleteuser
	@adeqo_user = AdeqoUser.find(params[:id])
	if @adeqo_user.destroy
		redirect_to @adeqo_user, alert: "User deleted successfully."
	else
		redirect_to adeqo_users_new_path, alert: "Error deleting user."
	end
end

end

app/helpers/adeqo_users_helper.rb
module AdeqoUsersHelper
end

app/views/adeqo_users/create.html.erb
<h1>AdeqoUsers#create</h1>
<p>Find me in app/views/adeqo_users/create.html.erb</p>

app/views/adeqo_users/index.html.erb
<!--
<h1>AdeqoUsers#index</h1>
<p>Find me in app/views/adeqo_users/index.html.erb</p>
-->

<h2>Adeqo Users Index Page</h2>

<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Email</th>
        <th scope="col">Password</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody>
      <% @adeqo_users.each_with_index do |user, index| %>
        <tr>
          <th scope="row"><%= index + 1 %></th>
          <td><%= user.email %></td>
          <td><%= user.password %></td>
	  <td>
            <%= link_to "Show User", { :controller => "adeqo_users", :action => "show", :id => user.id}, class: "btn btn-sm btn-primary" %>
            <!--<%= link_to "Update User", { :controller => "adeqo_users", :action => "updateuser", :id => user.id}, class: "btn btn-sm btn-info" %>-->
            <%= button_to "Delete User", { :controller => "adeqo_users", :action => "deleteuser", :id => user.id}, class: "btn btn-sm btn-danger" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= link_to "Add More Users", { :controller => "adeqo_users", :action => "new"} %>

app/views/adeqo_users/new.html.erb
<!--
<h1>AdeqoUsers#new</h1>
<p>Find me in app/views/adeqo_users/new.html.erb</p>
-->
<!DOCTYPE html>
<html lang="en">

  <head>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Sign Up Form</title>


    <!-- Custom fonts for this template NOT WORKING -->
<!--
    <link href="https://blackrockdigital.github.io/startbootstrap-landing-page/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
-->
    <link href="https://blackrockdigital.github.io/startbootstrap-landing-page/vendor/simple-line-icons/css/simple-line-icons.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">


    <!-- Custom styles for this template -->
    <link href="css/landing-page.min.css" rel="stylesheet">

  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-light bg-light static-top">
      <div class="container">
        <a class="navbar-brand" href="#">Adeqo</a>
      </div>
    </nav>

<% @page_title = "UserAuth | Signup" %>
<div class="Sign_Form">
  <h1>Almost there!</h1>
  <div class = "sign_desc"> Complete the sign up form below to get everything out of your Adeqo experience.</div>
 <p><br /><%= form_for(:adeqo_user, :url => {:controller => 'adeqo_users', :action => 'create'}) do |f| %></p>
    <p>  <%= f.email_field :email, placeholder: "Email", :required => true %> </p>
    <p><br /> <%= f.password_field :password, placeholder: "Password", :required => true %></p>
    <p><br /> <%= f.password_field :password_confirmation, placeholder: "Password Again", :required => true %> </p>
    <p><br /><%= f.submit :Signup %></p>
  <% end %>
  <% if @adeqo_user.errors.any? %>
    <ul class="Signup_Errors">
    <% for message_error in @adeqo_user.errors.full_messages %>
      <li>* <%= message_error %></li>
    <% end %>
    </ul>
  <% end %>
  <%= link_to "Back to Index", welcome_homepage_path %>
</div>



<!--
<h1>Add New User to Adeqo</h1>

<table>
  <%= form_for(@adeqo_user) do |f| %>
  <tr>
    <td><%= f.label :username %></td>
    <td><%= f.email_field :username, placeholder: "Email", :required => true %></td>
  </tr>
  <tr>
    <td><%= f.label :password %></td>
    <td><%= f.text_field :password, placeholder: "Password", :required => true %></td>
  </tr>
  <tr>
    <td><%= f.submit %></td>
  </tr>
  <% end %>
</table>

<%= link_to "Back to Index", adeqo_users_path %>
-->

app/views/adeqo_users/show.html.erb
<!--
<h1>AdeqoUsers#show</h1>
<p>Find me in app/views/adeqo_users/show.html.erb</p>
-->

<h1>Adeqo User Created Successfully</h1>

<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Email</th>
        <th scope="col">Password</th>
      </tr>
    </thead>
    <tbody>
        <tr>
          <td><%= @adeqo_users.email %></td>
          <td><%= @adeqo_users.password %></td>
        </tr>
    </tbody>
  </table>
</div>

<%= link_to "Back to Index", adeqo_users_path %>

app/views/adeqo_users/update.html.erb
<h1>Update User Profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
      <%= render 'shared/error_messages' %>

      <%= f.label :username %>
      <%= f.text_field :username, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
  </div>
</div>