config/routes.rb
Rails.application.routes.draw do
  devise_for :adeqo_users
  get 'adeqo_users/index'
  get 'adeqo_users/new'
  get 'adeqo_users/create'
 post 'adeqo_users/create'
  get 'adeqo_users/show'
  get 'create/new'
  get 'create/show'
  get 'users/index'
  get 'users/new'
  get 'users/create'
  get 'users/show'
  get 'users/error'
 post 'users/update'
# get 'users/downloadkwdump'
# resources :students
  resources :users
  resources :adeqo_users

  get 'welcome/index'
 #For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 #root 'application#hello'
 get 'welcome/homepage'

constraints subdomain: "alpha" do
        #get '/'=> redirect { |params| "http://alpha.adeqo.com/users/index" }
        get '/' => 'users#index'
end
  root 'welcome#homepage'

post 'users/downloadkwdump' => "users#downloadkwdump"
post 'users/updatead' => "users#updatead"

 get 'chris/test' => "chris#test"

post 'users/updateaccount' => "users#updateaccount"
post 'users/deleteaccount' => "users#deleteaccount"

post 'adeqo_users/updateuser' => "adeqo_users#updateuser"
post 'adeqo_users/deleteuser' => "adeqo_users#deleteuser"




end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

require "threesixty.rb"
require "sogou.rb" # not work yet, to fix

def index
	@users = User.all
end

def new
	@user = User.new
end

def create
	@user = User.new(params.require(:comments).permit(:commenter, :body))
	if @user.save
		redirect_to @user, alert: "User created successfully."
	else
		redirect_to new_user_path, alert: "Error creating user."
	end
end

def show
	@users = User.find(params[:id])
end

def updateaccount
	@user =  User.find(params[:id])
end

def deleteaccount
	@user = User.find(params[:id])
	if @user.destroy
		redirect_to @user, alert: "User Deleted successfully."
	else
		redirect_to new_user_path, alert: "Error deleting user."
	end
end

def error
	@error = Error.new(params[:object])
end 

#function takes a USER ID and finds what channel and then calls the corresponding channel ID

def downloadkwdump
	@user = User.find(params[:id])
	if @user.channel == "Sogou"
		sogou_update_kw(@user.username,@user.password,@user.apitoken)
		return
	end

	if @user.channel == "360"
		threesixty_update_kw(@user.username,@user.password,@user.apitoken, @user.apisecret)
		return
	end
end

def updatead 
	@user = User.find(params[:id])
	if @user.channel == "Sogou"
		sogou_update_ad(@user.username,@user.password,@user.apitoken)
		return
	end

	if @user.channel == "360"
		threesixty_update_ad(@user.username,@user.password,@user.apitoken, @user.apisecret)
		return
	end
end
 
#function to take a set of username, password and apitoken and output a list of URLs

def sogou_update_ad(username, password, apitoken)

	@username = username
	@password = password
	@apitoken = apitoken
	@group_id_array = []
	@ad_arr = []
	groupbegin = 0 # set 0 to start from the beginning
	totalchanges = 0

        sogou_api(@username, @password, @apitoken, "CpcGrpService")
        @update_status = @sogou_api.call(:get_all_cpc_grp_id)
	#@header = @update_status.header.to_hash
	#@msg = @header[:res_header][:desc]
	#@remain_quote = @header[:res_header][:rquota]
	#logger.info "[Sogou][AD] Quota [" + @remain_quote.to_s + "]"
	@update_status_body = @update_status.body.to_hash
	@result_active_grp = @update_status_body[:get_all_cpc_grp_id_response][:cpc_plan_grp_ids]
	@result_active_grp.each do |el|
		if el[:cpc_grp_ids].is_a?(Array)
			el[:cpc_grp_ids].each do |id| @group_id_array << id end
		else
			@group_id_array << el[:cpc_grp_ids]
		end
	end
	sogou_api(@username, @password, @apitoken, "CpcIdeaService")
	#logger.info @group_id_array.size #22144
	#@group_id_array = ["238876896", "238895734", "215628567"] #index 20106, 20107(nil), 20108
	@group_id_array[groupbegin..-1].each_with_index do |groupid, index|
		changes = 0
		@index = index + 1 + groupbegin
		@info = "[Sogou|AD|" + @username + "] [" + groupid.to_s + "][" + @index.to_s + "/" + @group_id_array.size.to_s + "] "
		logger.info @info + "Begin"
		@update_status = @sogou_api.call(:get_cpc_idea_by_cpc_grp_id, message: { cpcGrpIds: groupid, getTemp: 0 }) 
		@header = @update_status.header.to_hash
		#logger.info @msg = @header[:res_header][:desc]
		@remain_quote = @header[:res_header][:rquota]
		@update_status_body = @update_status.body.to_hash
		@result_active_cpc = @update_status_body[:get_cpc_idea_by_cpc_grp_id_response][:cpc_grp_ideas]
		#logger.info "[Sogou][AD] " + @result_active_cpc.to_s
		if @result_active_cpc[:cpc_idea_types].nil? then next end
		if !@result_active_cpc[:cpc_idea_types].nil?
	 		#logger.info "[Sogou] CPC Size [" + @result_active_cpc[:cpc_idea_types].size.to_s + "]"
			if @result_active_cpc[:cpc_idea_types].is_a?(Array)
				@ad_arr = @result_active_cpc[:cpc_idea_types]
			else
				@ad_arr << @result_active_cpc[:cpc_idea_types]
			end
			#logger.info @info + "All AD Size: [" + @ad_arr.size.to_s + "] All AD: " + @ad_arr.to_s
			request_arr = []
			@ad_arr.each do |ad|
				#logger.info @info + "AD: " + ad.to_s
				request = {}
				if (ad[:visit_url]) && (ad[:visit_url].include? "adeqo")
					@new_url= URI.unescape(ad[:visit_url].scan(/=(http[^>]*)/).last.first)
					request[:cpcIdeaId] = ad[:cpc_idea_id]
					request[:visitUrl] = @new_url
				end
				if (ad[:mobile_visit_url]) && (ad[:mobile_visit_url].include? "adeqo")
					@new_url= URI.unescape(ad[:mobile_visit_url].scan(/=(http[^>]*)/).last.first)
					request[:cpcIdeaId] = ad[:cpc_idea_id]
					request[:mobileVisitUrl] = @new_url
				end
				if request.size.to_i == 0 then next end
				request_arr << request
				changes = changes + 1
				rescue Timeout::Error
					logger.info "Timeout... waiting 30s then trying again"
					sleep(30)
				redo
			end 
		end
		#logger.info @info + "Request Size: [" + request_arr.size.to_s + "] Request: " + request_arr.to_s
		if request_arr.size.to_i == 0 then next end
		request_arr.each_slice(500) do |sub_arr| # set a number less than max number of API
			@result = @sogou_api.call(:update_cpc_idea, message: {cpcIdeaTypes: sub_arr})
			@header = @result.header.to_hash
			@update_response = @header[:res_header][:desc]
			if @update_response.to_s.downcase == "success"
				changes = changes + sub_arr.size
			end
		end
		if changes > 0
			totalchanges = totalchanges + changes
			logger.info @info + "Changes [" + changes.to_s + "] End"
		end
		#return
	end
	logger.info @info + "Total Changes [" + totalchanges.to_s + "] End"
	#return

end

#function to take a set of username, password and apitoken and output a list of URLs

def sogou_update_kw(username, password, apitoken)

	@username = username
	@password = password
	@apitoken = apitoken
	@group_id_array = []
	@kw_arr = []
	groupbegin = 0 # set 0 to start from the beginning
	totalchanges = 0

	#@group_id_array = sogou_groupid(@username, @password, @apitoken) #not work yet, to fix
	#logger.info @group_id_array.size
	#return

        sogou_api(@username, @password, @apitoken, "CpcGrpService")
        @update_status = @sogou_api.call(:get_all_cpc_grp_id)
	#@header = @update_status.header.to_hash
	#@msg = @header[:res_header][:desc]
	#@remain_quote = @header[:res_header][:rquota]
	#logger.info "[Sogou][KW] Quota [" + @remain_quote.to_s + "]"
	@update_status_body = @update_status.body.to_hash
	@result_active_grp = @update_status_body[:get_all_cpc_grp_id_response][:cpc_plan_grp_ids]
	@result_active_grp.each do |el|
		if el[:cpc_grp_ids].is_a?(Array)
			el[:cpc_grp_ids].each do |id| @group_id_array << id end
		else
			@group_id_array << el[:cpc_grp_ids]
		end
	end
	sogou_api(@username, @password, @apitoken, "CpcService")
	#logger.info @group_id_array.size #22144
	#@group_id_array = ["238876896", "238895734", "215628567"] #index 20106, 20107(nil), 20108
	@group_id_array[groupbegin..-1].each_with_index do |groupid, index|
		changes = 0
		@index = index + 1 + groupbegin
		@info = "[Sogou|KW|" + @username + "] [" + groupid.to_s + "][" + @index.to_s + "/" + @group_id_array.size.to_s + "] "
		logger.info @info + "Begin"
		@update_status = @sogou_api.call(:get_cpc_by_cpc_grp_id, message: { cpcGrpIds: groupid, getTemp: 0 }) 
		@header = @update_status.header.to_hash
		#logger.info @msg = @header[:res_header][:desc]
		@remain_quote = @header[:res_header][:rquota]
		@update_status_body = @update_status.body.to_hash
		@result_active_cpc = @update_status_body[:get_cpc_by_cpc_grp_id_response][:cpc_grp_cpcs]
		#logger.info "[Sogou][KW] " + @result_active_cpc.to_s
		if @result_active_cpc[:cpc_types].nil? then next end
		if !@result_active_cpc[:cpc_types].nil?
	 		#logger.info "[Sogou] CPC Size [" + @result_active_cpc[:cpc_types].size.to_s + "]"
			if !@result_active_cpc[:cpc_types].is_a?(Array)
				@kw_arr << @result_active_cpc[:cpc_types]
			else
				@kw_arr = @result_active_cpc[:cpc_types]
			end
			#logger.info @info + "All KW Size: [" + @kw_arr.size.to_s + "] All KW: " + @kw_arr.to_s
			#return
			request_arr = []
			@kw_arr.each do |kw|
				#logger.info @info + "KW: " + kw.to_s
				request = {}
				if (kw[:visit_url]) && (kw[:visit_url].include? "adeqo")
					@new_url= URI.unescape(kw[:visit_url].scan(/=(http[^>]*)/).last.first)
					request[:cpcId] = kw[:cpc_id]
					request[:visitUrl] = @new_url
				end
				if (kw[:mobile_visit_url]) && (kw[:mobile_visit_url].include? "adeqo")
					@new_url= URI.unescape(kw[:mobile_visit_url].scan(/=(http[^>]*)/).last.first)
					request[:cpcId] = kw[:cpc_id]
					request[:mobileVisitUrl] = @new_url
				end
				if request.size.to_i == 0 then next end
				request_arr << request
				changes = changes + 1
				rescue Timeout::Error
					logger.info "Timeout... waiting 30s then trying again"
					sleep(30)
				redo
			end 
		end
		#logger.info @info + "Request Size: [" + request_arr.size.to_s + "] Request: " + request_arr.to_s
		if request_arr.size.to_i == 0 then next end
		request_arr.each_slice(500) do |sub_arr| # set a number less than max number of API
			@result = @sogou_api.call(:update_cpc, message: {cpcTypes: sub_arr})
			@header = @result.header.to_hash
			@update_response = @header[:res_header][:desc]
			if @update_response.to_s.downcase == "success"
				changes = changes + sub_arr.size
			end
		end
		if changes > 0
			totalchanges = totalchanges + changes
			logger.info @info + "Changes [" + changes.to_s + "] End"
		end
		#return
	end
	logger.info @info + "Total Changes [" + totalchanges.to_s + "] End"
	#return

=begin
	rescue
	logger.info "-----Error Class-----"
	logger.info $!.class
	logger.info $@.class
	logger.info "-----Error Message-----"
	logger.info $!
	logger.info $@[0]

	@error = []
	@error << $i.class << $i << $@.class << $@[0]
	render plain: @error
	#render plain: "hello"
	#render :json => @error
	#render :action => "error", :error => @error #not work yet
=end

end

#Function Takes a User Credential and then calls the ad and kw level. all functions in threesixty.rb Updates the KW URL

def threesixty_update_ad(username,password,apitoken,apisecret)

	campaigns_array = ['携程错拼_phrase']
	groups_array = ['booking_phrase','agoda_phrase']
	@username = username
	@password = password
	@apitoken = apitoken
	@apisecret = apisecret

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/error.html.erb
<html>
<h1>Our Log Report</h1>
<table>


<% form_for(@error) do |f| %>

  <td><%= f %></td>

<% end %>

</table>
</html>

app/views/users/index.html.erb
<h2>Your Account Page</h2>

<div class="table-responsive">
  <table class="table">
    <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Channel</th>
          <th scope="col">Email</th>
          <th scope="col">Username</th>
          <!--<th scope="col">Password</th>-->
          <th scope="col">APIToken</th>
          <th scope="col">APISecret</th>
          <th scope="col">KW Action</th>
          <th scope="col">AD Action</th>
	  <!--<th scope="col">Account Action</th>-->
        </tr>
      </thead>
      <tbody>
        <% @users.each_with_index do |user, index| %>
          <tr>
            <th scope="row"><%= index + 1 %></th>
            <td><%= user.channel %></td>
            <td><%= user.email %></td>
            <td><%= user.username %></td>
            <!--<td>*******</td>-->
            <td><%= user.apitoken %></td>
            <td><%= user.apisecret %></td>
            <td><%= button_to "Delete Adeqo URLs", { :controller => "users", :action => "downloadkwdump", :id => user.id}, class: "btn btn-sm btn-warning" %> </td>
               <td><%= button_to "Delete Adeqo URLs", { :controller => "users", :action => "updatead", :id => user.id}, class: "btn btn-sm btn-warning" %> </td>

		<!--<td><%= button_to "Delete Account", { :controller => "users", :action => "deleteaccount", :id => user.id}, class: "btn btn-sm btn-danger", :disabled => true %></td>-->
          </tr>
        <% end %>
      </tbody>
  </table>
</div>

<!--<%= link_to "Add More Accounts", { :controller => "users", :action => "new"}, :class => "btn btn-sm btn-success" %>-->
<!-- <button onclick="window.location.href='/users/new'">Add More Accounts</button> -->

app/views/users/new.html.erb
<html>
<h1>Add Channel Accounts to Adeqo</h1>
<table>

<%= form_for(@user) do |f| %>
<tr>
<td><%= f.label :email %></td>
 <td>   <%= f.text_field :email %></td>
</tr>
<tr>
<td><%= f.label :username %></td>
<Td> <%= f.text_field :username %></td>
</tr>
<tr>
 <td>   <%= f.label :password %></td>
<td>    <%= f.text_field :password %></td>
</tr>

<tr>
<Td>    <%= f.label :apitoken %></td>

<td>    <%= f.text_field :apitoken %></td>
</tr>
<tr>
<Td>    <%= f.label :apisecret %></td>

<td>    <%= f.text_field :apisecret %></td>
</tr>

<tr>
<td> <%= f.label :channel %></td>

<td>    <%= f.select :channel, ['360', 'Sogou']%></td>
</tr>
<tr><td>
<%= f.submit%>
</td>
</tr>
<% end %>

</table>
</html>

app/views/users/show.html.erb
<h1>A New User Was Created</h1>
<p>Thanks!</p>


<%= link_to "Back", users_path %>

app/views/users/update.html.erb
<html>
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>


<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :username %>
      <%= f.text_field :username, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

</html>